### ISSUE TITLE
I have encountered a difficulty.

### ISSUE THREAD

**Issue by zjq-learn** [sp-uhh/storm#16]
I have encountered a difficulty as shown below, and I cannot find a solution online. Please help me with some guidance. Thank you very much.

ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).

**Comment by jmlemercier** [comment]
Hi,
Can you give the full stacktrace, provide your environment settings, package versions etc. 
Where odes it happen? At training, inference, which part of the repo?

**Comment by DIdididi0** [comment]
I encountered the same issue. Here's how I solved it: I reinstalled the pesq package in my conda virtual environment. The reason was that the package was not installed.

**Comment by Lieber0402** [comment]
> Hi, Can you give the full stacktrace, provide your environment settings, package versions etc. Where odes it happen? At training, inference, which part of the repo?

It's something like this:
Traceback (most recent call last):
  File "train.py", line 6, in <module>
    import pytorch_lightning as pl
  File "E:\anaconda3\envs\storm\lib\site-packages\pytorch_lightning\__init__.py", line 35, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "E:\anaconda3\envs\storm\lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "E:\anaconda3\envs\storm\lib\site-packages\pytorch_lightning\callbacks\batch_size_finder.py", line 24, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "E:\anaconda3\envs\storm\lib\site-packages\pytorch_lightning\callbacks\callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "E:\anaconda3\envs\storm\lib\site-packages\pytorch_lightning\utilities\types.py", line 27, in <module>
    from torchmetrics import Metric
  File "E:\anaconda3\envs\storm\lib\site-packages\torchmetrics\__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "E:\anaconda3\envs\storm\lib\site-packages\torchmetrics\functional\__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate
  File "E:\anaconda3\envs\storm\lib\site-packages\torchmetrics\functional\audio\__init__.py", line 23, in <module>
    from torchmetrics.functional.audio.pesq import perceptual_evaluation_speech_quality  # noqa: F401
  File "E:\anaconda3\envs\storm\lib\site-packages\torchmetrics\functional\audio\pesq.py", line 22, in <module>
    import pesq as pesq_backend
  File "E:\anaconda3\envs\storm\lib\site-packages\pesq\__init__.py", line 5, in <module>
    from ._pesq import pesq, pesq_batch
  File "E:\anaconda3\envs\storm\lib\site-packages\pesq\_pesq.py", line 8, in <module>
    from .cypesq import cypesq, cypesq_retvals, cypesq_error_message as pesq_error_message
  File "pesq\\cypesq.pyx", line 1, in init cypesq
ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).

It has mentioned about the error just like the earlier one.

**Comment by jmlemercier** [comment]
Yes as @DIdididi0 suggested, this is related to the PESQ packages. Please install it via pip before running either inference or training.
